# Generated by Django 3.2.4 on 2021-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(max_length=100)),
                ('assetname', models.CharField(max_length=100)),
                ('asset_make', models.CharField(max_length=100)),
                ('asset_model', models.CharField(max_length=100)),
                ('slno', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('pmdone', models.DateField(blank=True)),
                ('pmdue', models.DateField(blank=True)),
                ('pmstat', models.CharField(max_length=100)),
                ('caldue', models.DateField(blank=True)),
                ('caldone', models.DateField(blank=True)),
                ('calstat', models.CharField(max_length=100)),
                ('stat', models.CharField(max_length=100)),
            ],
        ),
    ]
